name: 'ArgoCD'
description: 'GitHub Action for ArgoCD'
inputs:
  version:
    description: 'Version'
    required: true
    default: 'latest'
  command:
    description: 'Command'
    required: true
    default: 'argocd version'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
